### ISSUE TITLE
Error importing futures

### ISSUE THREAD

**Issue by Chakerbh** [XayOn/python-simpletorrentstreaming#1]
When I try to import `SimpleTorrentStreaming`

    Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
    [GCC 4.8.2] on linux2
    >>> from SimpleTorrentStreaming import SimpleTorrentStreaming

I get this error

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/SimpleTorrentStreaming/SimpleTorrentStreaming.py", line 7, in <module>
        from futures import ThreadPoolExecutor
    ImportError: No module named futures
Which tell me to install the [`futures`](https://pypi.python.org/pypi/futures/3.0.3) module, and I did:

    $ pip freeze
    ....
    futures==3.0.3
    ....

However I still getting the same error.

**Comment by XayOn** [comment]
Thanks!

I've done a few major changes now, as a library I was using is not available anymore, and the code was not as clear as it should be. I did it as part of another project for making it easier to play stuff on a RPI v1, but I got a v2 and left this one behind, unfinished.

It's just a ~200 lines of code simple library for streaming torrents (yet now, if you've got mplayer installed, it has a CLI command for directly playing a torrent.

Thank you for reminding me this project was still alive, and hoping to get a more feedback from it.

Greetings.
